/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/a321.glb -o src/app/models/a321.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PlaneA321(props) {
  const { nodes, materials } = useGLTF('/models/a321.glb')
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh geometry={nodes.Mesh012.geometry} material={materials['0132_LightGray']} />
        <mesh geometry={nodes.Mesh012_1.geometry} material={materials['0128_White']} />
        <mesh geometry={nodes.Mesh012_2.geometry} material={materials['[Translucent_Glass_Gray]1']} />
        <mesh geometry={nodes.Mesh012_3.geometry} material={materials.Material6} />
        <mesh geometry={nodes.Mesh012_4.geometry} material={materials.skp_front_default} />
        <mesh geometry={nodes.Mesh012_5.geometry} material={materials.Color_008} />
        <mesh geometry={nodes.Mesh012_6.geometry} material={materials.Material9} />
        <mesh geometry={nodes.Mesh012_7.geometry} material={materials.Color_D06} />
        <mesh geometry={nodes.Mesh012_8.geometry} material={materials.Material7} />
        <mesh geometry={nodes.Mesh012_9.geometry} material={materials.Color_A06} />
        <mesh geometry={nodes.Mesh012_10.geometry} material={materials.Material8} />
        <mesh geometry={nodes.Mesh012_11.geometry} material={materials.Color_009} />
        <mesh geometry={nodes.Mesh012_12.geometry} material={materials.Color_I11} />
        <mesh geometry={nodes.Mesh012_13.geometry} material={materials['<LightGray>']} />
        <mesh geometry={nodes.Mesh012_14.geometry} material={materials['<Black>']} />
        <mesh geometry={nodes.Mesh012_15.geometry} material={materials['<Gainsboro>']} />
        <mesh geometry={nodes.Mesh012_16.geometry} material={materials['<Silver>']} />
        <mesh geometry={nodes.Mesh012_17.geometry} material={materials['<DarkGray>1']} />
        <mesh geometry={nodes.Mesh012_18.geometry} material={materials.Color_000} />
        <mesh geometry={nodes.Mesh012_19.geometry} material={materials.Material1} />
        <mesh geometry={nodes.Mesh012_20.geometry} material={materials['0131_Silver']} />
        <mesh geometry={nodes.Mesh012_21.geometry} material={materials.Material12} />
        <mesh geometry={nodes.Mesh012_22.geometry} material={materials.Material2} />
        <mesh geometry={nodes.Mesh012_23.geometry} material={materials.Material13} />
        <mesh geometry={nodes.Mesh012_24.geometry} material={materials['0135_DarkGray']} />
        <mesh geometry={nodes.Mesh012_25.geometry} material={materials.Material10} />
        <mesh geometry={nodes.Mesh012_26.geometry} material={materials['0136_Charcoal']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/a321.glb')
