/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/a380.glb -o src/app/models/a380.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function PlaneA380(props) {
  const { nodes, materials } = useGLTF('/models/a380.glb')
  return (
    <group rotation={[0, Math.PI, 0]} {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.wings} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.engines} />
      <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Cube001_3.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.Cube001_4.geometry} material={materials.Material} />
      <mesh geometry={nodes.Cube001_5.geometry} material={materials.plane} />
    </group>
  )
}

useGLTF.preload('/models/a380.glb')
